In [1]:
# Write a NumPy program to print the NumPy version on your system.

import numpy as np

print(np.__version__)

1.24.3


In [2]:
# Write a NumPy program to convert a list of numeric values into a one-dimensional NumPy array.
# Expected Output:
# Original List: [12.23, 13.32, 100, 36.32]
# One-dimensional NumPy array: [ 12.23 13.32 100. 36.32]

lst = [12.23, 13.32, 100, 36.32]
arr = np.array(lst)
print(arr)

[ 12.23  13.32 100.    36.32]


In [6]:
# Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.
# Expected Output:
# [[ 2 3 4]
# [ 5 6 7]
# [ 8 9 10]]

arr = np.arange(2,11).reshape(3,3)
arr

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [8]:
# Write a NumPy program to create a null vector of size 10 and update the sixth value to 11.
# [ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
# Update sixth value to 11
# [ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]

arr = np.zeros(10)
print(arr)
arr[6] = 11
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


In [10]:
# Write a NumPy program to create an array with values ranging from 12 to 38.
# Expected Output:
# [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]

arr = np.arange(12,38)
print(arr)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


In [13]:
# Write a NumPy program to reverse an array (the first element becomes the last).
# Original array:
# [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]
# Reverse array:
# [37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]

arr = np.arange(12,38)

print('Reverse of the array arr is : \n', arr[::-1])

Reverse of the array arr is : 
 [37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


In [15]:
# Write a NumPy program to convert an array to a floating type.
# Sample output:
# Original array
# [1, 2, 3, 4]
# Array converted to a float type:
# [ 1. 2. 3. 4.]

lst = [1, 2, 3, 4]
arr = np.array(lst)

arr1 = arr.astype(float)
print(arr1)

[1. 2. 3. 4.]


In [20]:
# Write a NumPy program to create a 2D array with 1 on the border and 0 inside.
# Expected Output:
# Original array:
# [[ 1. 1. 1. 1. 1.]
# ...................
# [ 1. 1. 1. 1. 1.]]
# 1 on the border and 0 inside in the array
# [[ 1. 1. 1. 1. 1.]
# ...................
# [ 1. 1. 1. 1. 1.]]

x = np.ones((5,5))
print('Original array \n', x)
x[1:-1, 1:-1] = 0
print('array with ones on the border and zeros in the middle : \n', x)

Original array 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
array with ones on the border and zeros in the middle : 
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [25]:
# Write a NumPy program to add a border (filled with 0's) around an existing array.
# Expected Output:
# Original array:
# [[ 1. 1. 1.]
# [ 1. 1. 1.]
# [ 1. 1. 1.]]
# 1 on the border and 0 inside in the array
# [[ 0. 0. 0. 0. 0.]
# ...........
# [ 0. 0. 0. 0. 0.]]

x = np.ones((3,3))
print('original array: \n', x)

x = np.pad(x, pad_width = 1, mode = 'constant', constant_values = 0)
print('1 on the border and 0 inside in the array \n', x)

original array: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
1 on the border and 0 inside in the array 
 [[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [2]:
# Write a NumPy program to create an 8x8 matrix and fill it with a checkerboard pattern.
# Checkerboard pattern:
# [[0 1 0 1 0 1 0 1]
# ..........
# [0 1 0 1 0 1 0 1]
# [1 0 1 0 1 0 1 0]]
import numpy as np

x = np.zeros((8,8))

x[1::2, ::2] = 1
x[::2, 1::2] = 1

print(x)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [5]:
# Write a NumPy program to append values to the end of an array.
# Expected Output:
# Original array:
# [10, 20, 30]
# After append values to the end of the array:
# [10 20 30 40 50 60 70 80 90]

a = np.array([10,20,30])
b = np.array([40, 50, 60, 70, 80])

a = np.append(a,b)
print(a)

[10 20 30 40 50 60 70 80]


In [8]:
# Write a NumPy program to create an empty and full array.
# Expected Output:
# [ 6.93270651e-310 1.59262180e-316 6.93270559e-310 6.93270665e-310]
# [ 6.93270667e-310 6.93270671e-310 6.93270668e-310 6.93270483e-310]
# [ 6.93270668e-310 6.93270671e-310 6.93270370e-310 6.93270488e-310]]
# [[6 6 6]
# [6 6 6]
# [6 6 6]]

a = np.empty((3,4))
print(a)
b = np.full((3,3), 6)
print(b)

[[8.50778157e-312 3.16202013e-322 0.00000000e+000 0.00000000e+000]
 [7.56587583e-307 1.28966143e+165 1.33920410e-075 1.64825138e+185]
 [1.84806868e-076 2.80535071e-032 6.16963457e-062 1.17740840e-047]]
[[6 6 6]
 [6 6 6]
 [6 6 6]]


In [11]:
# Write a NumPy program to convert Centigrade degrees into Fahrenheit degrees. Centigrade values are stored in a NumPy array.
# Sample Array [0, 12, 45.21, 34, 99.91]
# [-17.78, -11.11, 7.34, 1.11, 37.73, 0. ]
# Expected Output:
# Values in Fahrenheit degrees:
# [ 0. 12. 45.21 34. 99.91 32. ]
# Values in Centigrade degrees:
# [-17.78 -11.11 7.34 1.11 37.73 0. ]

# Values in Centigrade degrees:
# [-17.78 -11.11 7.34 1.11 37.73 0. ]
# Values in Fahrenheit degrees:
# [-0. 12. 45.21 34. 99.91 32. ]

fahn_values = [0, 12, 45.21, 34, 99.91]
f = np.array(fahn_values)
print('values in Fahrenheit degrees : \n', f)

cent_values = [-17.78, -11.11, 7.34, 1.11, 37.73, 0. ]
c = np.array([-17.78, -11.11, 7.34, 1.11, 37.73, 0. ])
print('Values in Centigrade degrees : \n', c)

print('Values converted to centigrade from fahrenheit degrees are : ')
print(np.round((5*f/9 - 5*32/9),2))

values in Fahrenheit degrees : 
 [ 0.   12.   45.21 34.   99.91]
Values in Centigrade degrees : 
 [-17.78 -11.11   7.34   1.11  37.73   0.  ]
Values converted to centigrade from fahrenheit degrees are : 
[-17.78 -11.11   7.34   1.11  37.73]


In [4]:
# Write a NumPy program to find the real and imaginary parts of an array of complex numbers.
# Expected Output:
# Original array [ 1.00000000+0.j 0.70710678+0.70710678j]
# Real part of the array:
# [ 1. 0.70710678]
# Imaginary part of the array:
# [ 0. 0.70710678]

import numpy as np

x = np.sqrt(1 + 0j)

y = np.sqrt(0 + 1j)

print('original array, x : \n', x)
print('original array, y : \n', y)

print('\nReal part of array x and y : ')
print(x.real)
print(y.real)

print('\nImaginary part of array x and y : ')
print(x.imag)
print(y.imag)



original array, x : 
 (1+0j)
original array, y : 
 (0.7071067811865476+0.7071067811865475j)

Real part of array x and y : 
1.0
0.7071067811865476

Imaginary part of array x and y : 
0.0
0.7071067811865475


In [8]:
# Write a NumPy program to sort pairs of a first name and a last name and return their indices (first by last name, then by first name).
first_names = ('Betsey', 'Shelley', 'Lanell', 'Genesis', 'Margery')
last_names = ('Battle', 'Brien', 'Plotner', 'Stahl', 'Woolum')

x = np.lexsort((first_names, last_names))

print('DISPLAY names in sorted pair lexicographically: \n')
print(x)



DISPLAY names in sorted pair lexicographically: 

[0 1 2 3 4]


In [9]:
# Write a NumPy program to get the values and indices of the elements that are bigger than 10 in a given array.

x = np.array([[0, 10, 20], [20, 30, 40]])

print('original array : \n')
print(x)

print('values bigger than 10 = ', x[x>10])

print('indices are ', np.nonzero(x > 10))

original array : 

[[ 0 10 20]
 [20 30 40]]
values bigger than 10 =  [20 20 30 40]
indices are  (array([0, 1, 1, 1], dtype=int64), array([2, 0, 1, 2], dtype=int64))
